import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Left from "@/components/Left";
import Right from "@/components/Right";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          <div className="row h-100">
            <div className="col-3 p-0 tbdr">
              <Left />
            </div>
            <div className="col-6 p-0 tbdr">
              {children}</div>
            <div className="col-3 p-0 tbdr">
              <Right />
            </div>
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
